### ISSUE TITLE
[US] Write React Component Tests

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#12]
**Statement**:

As a developer, I want to write manual tests so that I can ensure the functionality of my React components.

**Acceptance Criteria**:

- [x] Write unit tests for React components.
- [x] Ensure tests cover critical functionalities.
- [ ] Document test cases and results.

**Tasks**:

- [x] Create unit tests for React components.
- [x] Run and verify test coverage.
- [ ] Document test cases and results.

**Belonging to**:  EPIC - Development
