### ISSUE TITLE
[US] DRF - Write API Endpoint Tests

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#13]
**Statement**:

As a developer, I want to write tests so that I can verify the correctness of the API endpoints.

**Acceptance Criteria**:

- [x] Write unit tests for API endpoints.
- [x] Ensure tests cover critical API functionalities.
- [x] Document test cases and results.

**Tasks**:

- [x] Create unit tests for API endpoints.
- [x] Run and verify test coverage.
- [x] Document test cases and results. 

**Belonging to**:  EPIC - Development

**Comment by JaqiKal** [comment]
- Added test case files for Comments, Hashtags and Posts
