### ISSUE TITLE
[US] Sign Up for New Account

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#16]
**Statement**:

As a user I can create a new account so that I can access all the features for signed up users.

**Acceptance Criteria**:

- [x] Provide a sign-up form with username, email, and password fields.
- [x] Validate input fields to ensure all required information is provided.
- [x] Display error messages for invalid inputs.

**Tasks**:

- [x] Create a Sign-Up component with a form.
- [x] Implement form validation for input fields.
- [x] Connect the form to the backend API to create a new user.

**Belonging to**:  EPIC - Navigation & Authentication
