### ISSUE TITLE
[US] Sign In to Access Features

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#17]
**Statement**:

As a user I can sign in to the app so that I can access functionality for logged in users .

**Acceptance Criteria**:

- [x] Provide a sign-in form with email and password fields.
- [x] Validate input fields to ensure required information is provided.
- [x] Display error messages for invalid inputs.

**Tasks**:

- [x] Create a Sign-In component with a form.
- [x] Implement form validation for input fields.
- [x] Connect the form to the backend API to authenticate the user.

**Belonging to**:  EPIC - Navigation & Authentication
