### ISSUE TITLE
[US] Logged In Status Check

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#18]
**Statement**:

As a user I can tell if I am logged in or not so that I can log in if I need to.

**Acceptance Criteria**:

- [x] Display user’s name and avatar if logged in.
- [x] Show login/signup links if not logged in.
- [x] Update Navbar based on login status.

**Tasks**:

- [x] Implement a function to check login status.
- [x] Update Navbar to display user info or login/signup links.
- [x] Style the user info display.

**Belonging to**:  EPIC - Navigation & Authentication
