### ISSUE TITLE
[US] Maintain Logged-In Status

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#19]
**Statement**:

As a user I can maintain my logged-in status until I choose to log out so that my user experience is not compromised.

**Acceptance Criteria**:

- [x] Use refresh tokens to maintain session.
- [x] Automatically refresh tokens before they expire.
- [x] Display error message if token refresh fails.

**Tasks**:

- [x] Implement token refresh mechanism in the backend.
- [x] Update frontend to handle token refresh.
- [x] Test the token refresh functionality.

**Belonging to**:  EPIC - Navigation & Authentication
