### ISSUE TITLE
[US] Conditional Sign In/Up Options

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#20]
**Statement**:

As a logged out user I can see sign in and sign up options so that I can sign in/sign up.

**Acceptance Criteria**:

- [x] Display sign in and sign up links when logged out.
- [x] Hide sign in and sign up links when logged in.
- [x] Ensure correct links are displayed based on login status.

**Tasks**:

- [x] Implement conditional rendering for login status.
- [x] Update Navbar to show/hide links based on login status.
- [x] Style the links appropriately. 

**Belonging to**:  EPIC - Navigation & Authentication
