### ISSUE TITLE
[US] View User Avatars

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#21]
**Statement**:

As a user I can view user's avatars so that I can easily identify users of the application.

**Acceptance Criteria**:

- [x] Display user avatars on posts and comments.
- [x] Ensure avatars are displayed correctly and consistently.
- [x] Provide a default avatar for users without one.

**Tasks**:

- [x] Update user model to include avatar field.
- [x] Display avatars in relevant components (posts, comments).
- [x] Style avatars to ensure consistent display.

**Belonging to**:  EPIC - Navigation & Authentication
