### ISSUE TITLE
[US] Create New Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#22]
**Statement**:

As a logged in user I can create posts so that I can share my images with the world.

**Acceptance Criteria**:

- [x] Provide a form to create a new post with image upload.
- [x] Validate input fields to ensure required information is provided.
- [x] Display success message on successful post creation.

**Tasks**:

- [x] Create a CreatePost component with a form.
- [x] Implement form validation and image upload.
- [x] Connect the form to the backend API to create a new post.

**Belonging to**:  EPIC - Adding & Liking Posts
