### ISSUE TITLE
[US] Like Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#24]
**Statement**:

As a logged in user I can like a post so that I can show my support for the posts that interest me.

**Acceptance Criteria**:

- [x] Provide a like button on each post.
- [x] Update the like count in real-time.
- [x] Ensure a user can only like a post once.

**Tasks**:

- [x] Implement a like button component.
- [x] Update like count in the backend API.
- [ ] Style the like button and like count display.

**Belonging to**:  EPIC - Adding & Liking Posts
