### ISSUE TITLE
[US] Search Posts by Keywords

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#26]
**Statement**:

As a user, I can search for posts with keywords, so that I can find the posts and user profiles I am most interested in

**Acceptance Criteria**:

- [x] Provide a search input field.
- [x] Filter posts based on the search keyword.
- [x] Display search results dynamically.

**Tasks**:

- [x] Create a Search component with an input field.
- [x] Implement search functionality to filter posts.
- [x] Display filtered posts based on search input.

**Belonging to**:  [EPIC - The Posts Page](https://github.com/users/JaqiKal/projects/14/views/1?pane=issue&itemId=64892414)
