### ISSUE TITLE
[US] View Liked Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#27]
**Statement**:

As a logged in user I can view the posts I liked so that I can find the posts I enjoy the most.

**Acceptance Criteria**:

- [x] Display a list of posts the user has liked.
- [x] Ensure the list updates automatically with new likes.
- [x] Style the list for readability and accessibility.: 

**Tasks**:

- [x] Create a LikedPosts component.
- [x] Fetch and display liked posts from the backend API.
- [x] Style the liked posts list to ensure readability and accessibility.

**Belonging to**:  [EPIC - The Posts Page](https://github.com/JaqiKal/pixavibe-frontend/issues/58)
