### ISSUE TITLE
[US] View Followed Users' Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#28]
**Statement**:

As a logged in user I can view content filtered by users I follow so that I can keep up to date with what they are posting about.

**Acceptance Criteria**:

- [x] Display a list of posts from followed users.
- [x] Ensure the list updates automatically with new posts from followed users.
- [x] Style the list for readability and accessibility. 

**Tasks**:

- [x] Create a FollowedUsersPosts component.
- [x] Fetch and display posts from followed users from the backend API.
- [x] Style the posts list to ensure readability and accessibility.

**Belonging to**:  EPIC - The Posts Page
