### ISSUE TITLE
[US]  Add Hashtags to Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#30]
**Statement**:

As a user, I want to add hashtags to my posts so that they are easier to find.

**Acceptance Criteria**:

- [x] Provide an option to add hashtags when creating or editing a post.
- [x] Display hashtags along with posts.
- [ ] Ensure hashtags are saved and retrievable from the backend.

**Tasks**:

- [x] Update the CreatePost and EditPost components to include hashtags input.
- [ ] Connect the hashtags input to the backend API.
- [x] Display hashtags in the PostDetails component.

**Belonging to**:  EPIC - The Posts Page

**Comment by JaqiKal** [comment]
change wording to 'hashtags'

**Comment by JaqiKal** [comment]
Hashtag Error [BUG#68](https://github.com/JaqiKal/pixavibe-frontend/issues/68)
