### ISSUE TITLE
[US] Search Posts by hashtag 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#31]
**Statement**:

As a user, I want to search for posts by hashtag so that I can find related content.

**Acceptance Criteria**:

- [x] Provide a search input field for hashtag .
- [ ] Filter posts based on selected hashtag .
- [ ] Display filtered posts dynamically.

**Tasks**:

- [x] Create a hashtag search component with an input field.
- [ ] Implement search functionality to filter posts by hashtag .
- [ ] Display filtered posts based on selected hashtag .

**Belonging to**:  EPIC - The Posts Page

**Comment by JaqiKal** [comment]
Changed wordin to 'hashtag '

**Comment by JaqiKal** [comment]
Hashtag Error [BUG#68](https://github.com/JaqiKal/pixavibe-frontend/issues/68)
