### ISSUE TITLE
[US] View Post Page 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#32]
**Statement**:

As a user I can view the posts page so that I can read the comments about the post.

**Acceptance Criteria**:

- [x] Display post details including comments.
- [x] Ensure the comments are displayed in a readable format.
- [x] Allow users to scroll through comments if there are many.

**Tasks**:

- [x] Create a PostPage component.
- [x] Fetch and display comments for each post.
- [x] Style the comments section for readability.

**Belonging to**:  [EPIC - The Post Page
](https://github.com/JaqiKal/pixavibe-frontend/issues/59)
