### ISSUE TITLE
[US] Add Comments to Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#34]
**Statement**:

As a logged in user I can add comments to a post so that I can share my thoughts about the post.

**Acceptance Criteria**:

- [x] Provide a form to add comments.
- [x] Validate input fields to ensure required information is provided.
- [x] Display success message on successful comment creation.

**Tasks**:

- [x] Create a CommentForm component.
- [x] Implement form validation for the comment input field.
- [x] Connect the form to the backend API to create a new comment.

**Belonging to**:  [EPIC - The Post Page](https://github.com/JaqiKal/pixavibe-frontend/issues/59)
