### ISSUE TITLE
[US] Read Comments on Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#36]
**Statement**:

As a user I can read comments on posts so that I can read what other users think about the posts.

**Acceptance Criteria**:

- [x] Display comments below each post.
- [x] Ensure comments are displayed in a readable format.
- [x] Allow users to scroll through comments if there are many.

**Tasks**:

- [x] Fetch and display comments for each post.
- [x] Style the comments section for readability.
- [x] Implement scrolling for long comments sections.

**Belonging to**:  [EPIC - The Post Page](https://github.com/JaqiKal/pixavibe-frontend/issues/59)
