### ISSUE TITLE
[US] Delete My Comments 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#37]
**Statement**:

 As an owner of a comment I can delete my comment so that I can control removal of my comment from the application.

**Acceptance Criteria**:

- [x] Provide a delete button for comment owners.
- [x] Display success message on successful comment deletion.

**Tasks**:

- [x] Implement delete functionality for comments.
- [x] Connect the delete button to the backend API.

**Belonging to**:  EPIC - The Post Page
