### ISSUE TITLE
[US] View User Profiles 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#39]
**Statement**:

As a user I can view other users profiles so that I can see their posts and learn more about them.

**Acceptance Criteria**:

- [x] Display user profiles with bio, posts, and other relevant information.
- [x] Ensure profiles are accessible via a unique URL.
- [x] Style the profile page for readability and attractiveness.

**Tasks**:

- [x] Create a ProfilePage component.
- [x] Fetch and display user profile data from the backend API.
- [x] Style the profile page for readability and attractiveness.

**Belonging to**:  [EPIC - The Profile Page](https://github.com/JaqiKal/pixavibe-frontend/issues/60)
