### ISSUE TITLE
[US] View Most Followed Profiles

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#40]
**Statement**:

As a user I can see a list of the most followed profiles so that I can see which profiles are popular.

**Acceptance Criteria**:

- [x] Display a list of the most followed profiles.
- [x] Ensure the list is updated dynamically.
- [x] Style the list for readability and attractiveness.

**Tasks**:

- [x] Create a MostFollowedProfiles component.
- [x] Fetch and display most followed profiles from the backend API.
- [x] Style the list for readability and attractiveness.

**Belonging to**:  [EPIC - The Profile Page](https://github.com/JaqiKal/pixavibe-frontend/issues/60)
