### ISSUE TITLE
[US] View User Stats

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#41]
**Statement**:

As a user I can view statistics about a specific user: number of posts, follows and users followed so that I can learn more about them.

**Acceptance Criteria**:

- [x] Display user statistics including number of posts, follows, and followers.
- [x] Ensure statistics are updated dynamically.
- [x] Style the statistics section for readability and attractiveness.

**Tasks**:

- [x] Create a UserStats component.
- [x] Fetch and display user statistics from the backend API.
- [x] Style the statistics section for readability and attractiveness.

**Belonging to**:  EPIC - The Profile Page
