### ISSUE TITLE
[US] Follow/Unfollow Users 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#42]
**Statement**:

As a logged in user I can follow and unfollow other users so that I can see and remove posts by specific users in my posts feed.

**Acceptance Criteria**:

- [x] Provide follow/unfollow buttons on user profiles.
- [x] Update the follow status dynamically.
- [x] Display success message on successful follow/unfollow action.

**Tasks**:

- [x] Implement follow/unfollow functionality.
- [x] Connect the buttons to the backend API.
- [x] Style the follow/unfollow buttons.

**Belonging to**:  EPIC - The Profile Page
