### ISSUE TITLE
[US] View All Posts by specific User

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#43]
**Statement**:

 As a user I can view all the posts by a specific user so that I can catch up on their latest posts, or decide I want to follow them.

**Acceptance Criteria**:

- [x] Display a list of posts by a specific user.
- [x] Ensure the list is updated dynamically.
- [x] Style the list for readability and attractiveness.

**Tasks**:

- [x] Fetch and display posts by a specific user from the backend API.
- [x] Style the posts list for readability and attractiveness.
- [x] Ensure the list updates dynamically.

**Belonging to**:  [EPIC - The Profile Page](https://github.com/JaqiKal/pixavibe-frontend/issues/60)
