### ISSUE TITLE
[US] Edit My Profile

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#44]
**Statement**:

As a logged in user I can edit my profile so that I can change my profile picture and bio.

**Acceptance Criteria**:

- [x] Provide an edit profile form with fields for profile picture and bio.
- [x] Validate input fields to ensure required information is provided.
- [x] Display success message on successful profile edit.

**Tasks**:

- [x] Create an EditProfile component with a form.
- [x] Implement form validation for input fields.
- [x] Connect the form to the backend API to update the profile.

**Belonging to**:  [EPIC - The Profile Page](https://github.com/JaqiKal/pixavibe-frontend/issues/60)
