### ISSUE TITLE
[US] Update username and password

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#45]
**Statement**:

As a logged in user I can update my username and password so that I can change my display name and keep my profile secure.

**Acceptance Criteria**:

- [x] Provide a form to update username and password.
- [x] Validate input fields to ensure required information is provided.
- [x] Display success message on successful update. 

**Tasks**:

- [x] Create an UpdateCredentials component with a form.
- [x] Implement form validation for input fields.
- [x] Connect the form to the backend API to update credentials.

**Belonging to**:  EPIC - The Profile Page
