### ISSUE TITLE
[US] DRF - Implement Blocking/(hide) Functionality 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#46]
**Statement**:

As a developer, I want to implement a blocking functionality so that users do not have to see posts from users they have blocked.

**Acceptance Criteria**:

- [x] Users can block other users.
- [x]  Users that have blocked other users do not get search results including the blocked users.
- [x] Users do not see posts from blocked users in their feed.

**Tasks**:

- [x] Create a Block model in Django.
- [x] Implement backend logic to handle blocking, including updating search and feed queries to exclude blocked users.
- [x] Create frontend functionality to block users, including a block button on user profiles.

**Belonging to**:  EPIC - The Profile Page

**Comment by JaqiKal** [comment]
I resvised this us because during ths course  of coding I realised that teh wording is incorrect. Did not reflect what I wanted to achieve.
