### ISSUE TITLE
[US] Block/(Hide) Users

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#47]
**Statement**:

As a user, I want to be able to block other users so that they cannot interact with my content.

**Acceptance Criteria**:

- [x] Users can access the block option from the user profile.

**Tasks**:

- [x]  Add a block button to user profiles.

- [x] Update the user interface to reflect blocked status.

- [x]  Test the blocking functionality to ensure it works as expected.

**Belonging to**:  EPIC - The Profile Page

**Comment by JaqiKal** [comment]
Created a new us for removed acc criteria parts.
( Blocked users cannot see or interact with the user's posts.)

**Comment by JaqiKal** [comment]
In this first increment of development the user hides the other user, the blocked user can still see blockees posts
