### ISSUE TITLE
US: Design Responsive UI

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#5]
**Statement**:

As a developer, I want to design a responsive user interface using React so that users have a seamless experience across devices
Acceptance Criteria:

**Acceptance Criteria**:

- [ ] Create responsive layout components in React.
- [ ] Implement responsive UI components.
- [ ] Test and optimize the interface for different devices.

**Tasks**:

- [ ] Create responsive layout components in React.
- [ ] Implement responsive UI components.
- [ ] Test and optimize the interface for different devices.

**Belonging to**:  EPIC - Development
