### ISSUE TITLE
[US] Design Responsive UI

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#5]
**Statement**:

As a developer, I want to design a responsive user interface using React so that users have a seamless experience across devices.

**Acceptance Criteria**:

- [x] Design and implement a responsive layout.
- [x] Ensure UI components are responsive.
- [x] Test the interface on various devices.

**Tasks**:

- [x] Create responsive layout components in React.
- [x] Implement responsive UI components.
- [x] Test and optimize the interface for different devices.

**Belonging to**: [ EPIC - Desing & Implement UI](https://github.com/users/JaqiKal/projects/14/views/1?pane=issue&itemId=64881090)
