### ISSUE TITLE
[EPIC]: Set Up and Secure Django Rest Framework

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#53]
**Objective**: 

Set up the Django Rest Framework and secure user data for building and maintaining the API.

**Connected User Stories**:

- [x] [US: 7](https://github.com/JaqiKal/pixavibe-frontend/issues/7) - As a developer, I want to create a Django project and set up the Django Rest Framework so that I can build the API.

- [x] [US: 8](https://github.com/JaqiKal/pixavibe-frontend/issues/8) - As a developer, I want to design database models so that the data is structured logically.
- [x] [US: 9](https://github.com/JaqiKal/pixavibe-frontend/issues/9) - As a developer, I want to implement CRUD operations in the API so that users can manage their content.
- [x]  [US: 11](https://github.com/JaqiKal/pixavibe-frontend/issues/11) - As a developer, I want to secure user data by storing passwords hashed and ensuring sensitive information is protected.
