### ISSUE TITLE
[EPIC]: Navigation & Authentication

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#56]
**Objective**: 

Implement navigation and authentication features to enhance user experience and security.

**Connected User Stories**:

- [x] [US: 14](https://github.com/JaqiKal/pixavibe-frontend/issues/14) - As a user I can view a navbar from every page so that I can navigate easily between pages.
- [x] [US: 15](https://github.com/JaqiKal/pixavibe-frontend/issues/15) - As a user I can navigate through pages quickly so that I can view content seamlessly without page refresh.
- [x] [US: 16](https://github.com/JaqiKal/pixavibe-frontend/issues/16) - As a user I can create a new account so that I can access all the features for signed up users.
- [x] [US: 17](https://github.com/JaqiKal/pixavibe-frontend/issues/17) - As a user I can sign in to the app so that I can access functionality for logged in users.
- [x] [US: 18](https://github.com/JaqiKal/pixavibe-frontend/issues/18) - As a user I can tell if I am logged in or not so that I can log in if I need to.
- [x] [US: 19](https://github.com/JaqiKal/pixavibe-frontend/issues/19) - As a user I can maintain my logged-in status until I choose to log out so that my user experience is not compromised.
- [x] [US: 20](https://github.com/JaqiKal/pixavibe-frontend/issues/20) - As a logged out user I can see sign in and sign up options so that I can sign in/sign up.
- [x] [US: 21](https://github.com/JaqiKal/pixavibe-frontend/issues/21) - As a user I can view user's avatars so that I can easily identify users of the application.
