### ISSUE TITLE
[EPIC]: Adding & Liking Posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#57]
**Objective**: 

Enable users to create, view, and like posts to engage with the content.

**Connected User Stories**:

- [x]  [US: 22](https://github.com/JaqiKal/pixavibe-frontend/issues/22) - As a logged in user I can create posts so that I can share my images with the world!
- [x]  [US: 23](https://github.com/JaqiKal/pixavibe-frontend/issues/23) - As a user I can view the details of a single post so that I can learn more about it.
- [x]  [US: 24](https://github.com/JaqiKal/pixavibe-frontend/issues/24) - As a logged in user I can like a post so that I can show my support for the posts that interest me.
