### ISSUE TITLE
[EPIC]: The Posts Page

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#58]
**Objective**: 

Provide features to view and interact with posts, including searching and infinite scroll.

**Connected User Stories**:

- [x] [US: 25](https://github.com/JaqiKal/pixavibe-frontend/issues/25) - As a user I can view all the most recent posts, ordered by most recently created first so that I am up to date with the newest content.
- [x] [US: 26](https://github.com/JaqiKal/pixavibe-frontend/issues/26) - As a user, I can search for posts with keywords, so that I can find the posts and user profiles I am most interested in.
- [x] [US: 27](https://github.com/JaqiKal/pixavibe-frontend/issues/27) - As a logged in user I can view the posts I liked so that I can find the posts I enjoy the most.
- [x] [US: 28](https://github.com/JaqiKal/pixavibe-frontend/issues/28) - As a logged in user I can view content filtered by users I follow so that I can keep up to date with what they are posting about.
- [x] [US: 29](https://github.com/JaqiKal/pixavibe-frontend/issues/29) - As a user I can keep scrolling through the images on the site, that are loaded for me automatically so that I don't have to click on "next page" etc.
- [ ] [US: 30](https://github.com/JaqiKal/pixavibe-frontend/issues/30) - As a user, I want to add hashtags to my posts so that they are easier to find.
- [ ] [US: 31](https://github.com/JaqiKal/pixavibe-frontend/issues/31) - As a user, I want to search for posts by hashtags so that I can find related content.

- [x] [US:67](https://github.com/JaqiKal/pixavibe-frontend/issues/67) - As a user, I want to add category to my posts so that they are easier to find.

**Comment by JaqiKal** [comment]
Partly done but items that are left does not stop MVP. They are nice to haves.
