### ISSUE TITLE
[EPIC]: The Post Page

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#59]
**Objective**: 

Allow users to interact with individual posts, including viewing, commenting, editing, and deleting comments.

**Connected User Stories**:

- [x]  [US: 32](https://github.com/JaqiKal/pixavibe-frontend/issues/32) - As a user I can view the posts page so that I can read the comments about the post.
- [x]  [US: 33](https://github.com/JaqiKal/pixavibe-frontend/issues/33) - As a post owner I can edit my post title and description so that I can make corrections or update my post after it was created.
- [x]  [US: 34](https://github.com/JaqiKal/pixavibe-frontend/issues/34) - As a logged in user I can add comments to a post so that I can share my thoughts about the post.
- [x]  [US: 35](https://github.com/JaqiKal/pixavibe-frontend/issues/35) - As a user I can see how long ago a comment was made so that I know how old a comment is.
- [x]  [US: 36](https://github.com/JaqiKal/pixavibe-frontend/issues/36) - As a user I can read comments on posts so that I can read what other users think about the posts.
- [x]  [US: 37](https://github.com/JaqiKal/pixavibe-frontend/issues/37) - As an owner of a comment I can delete my comment so that I can control removal of my comment from the application.
- [x]  [US: 38](https://github.com/JaqiKal/pixavibe-frontend/issues/38) - As an owner of a comment I can edit my comment so that I can fix or update my existing comment.
