### ISSUE TITLE
[US] Create Reusable Components

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#6]
**Statement**:

As a developer, I want to create reusable components in React so that the codebase is maintainable and scalabl.

**Acceptance Criteria**:

- [x] Identify common UI elements for componentization.
- [x] Create reusable React components.
- [x] Ensure components are well-documented and tested.

**Tasks**:

- [x] List common UI elements for componentization.
- [x] Create and implement reusable React components.
- [x] Document and test the created components.

**Belonging to**: [ EPIC - Desing & Implement UI](https://github.com/users/JaqiKal/projects/14/views/1?pane=issue&itemId=64881090)
