### ISSUE TITLE
[EPIC]: The Profile Page

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#60]
**Objective**: 

Enable users to manage their profiles and interact with other user profiles.

**Connected User Stories**:

- [x]  [US: 39](https://github.com/JaqiKal/pixavibe-frontend/issues/39) - As a user I can view other users profiles so that I can see their posts and learn more about them.
- [x]  [US: 40](https://github.com/JaqiKal/pixavibe-frontend/issues/40) - As a user I can see a list of the most followed profiles so that I can see which profiles are popular.
- [x]  [US: 41](https://github.com/JaqiKal/pixavibe-frontend/issues/41) - As a user I can view statistics about a specific user: bio, number of posts, follows and users followed so that I can learn more about them.
- [x]  [US: 42](https://github.com/JaqiKal/pixavibe-frontend/issues/42) - As a logged in user I can follow and unfollow other users so that I can see and remove posts by specific users in my posts feed.
- [x] [US: 43](https://github.com/JaqiKal/pixavibe-frontend/issues/43) - As a user I can view all the posts by a specific user so that I can catch up on their latest posts, or decide I want to follow them.
- [x]  [US: 44](https://github.com/JaqiKal/pixavibe-frontend/issues/44) - As a logged in user I can edit my profile so that I can change my profile picture and bio.
- [x]  [US: 45](https://github.com/JaqiKal/pixavibe-frontend/issues/45) - As a logged in user I can update my username and password so that I can change my display name and keep my profile secure.
