### ISSUE TITLE
[US] Add category to posts

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#67]
**Statement**:

As a user, I want to add category to my posts so that they are easier to find.

**Acceptance Criteria**:

- [x] Provide an option to add category when creating or editing a post.
- [x] Display category along with posts.
- [x] Ensure category are saved and retrievable from the backend.

**Tasks**:

- [x] Update the CreatePost and EditPost components to include category input.
- [x] Connect the category input to the backend API.
- [x] Display category in the PostDetails component.

**Belonging to**:  EPIC - The Posts Page
