### ISSUE TITLE
[US] Add category filter

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#71]
**Statement**:

As a user, I want to be able to filter category so that posts are easier to find.

**Acceptance Criteria**:

- [x] Provide a dropdown or selection option for users to filter posts by category.
- [x] Display the category along with each post in the post listing.
- [x] The filter should be easily accessible and user-friendly.

**Tasks**:

- [x] Update the CreatePost and EditPost components to include a category input field.
- [x] Connect the category input to the backend API.
- [x] Create a CategoryFilter component that allows users to select a category to filter posts.

**Belonging to**:  EPIC - The Posts Page
