### ISSUE TITLE
US: DRF - Design Database Models 

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#8]
**Statement**:

As a developer, I want to design database models so that the data is structured logically 

**Acceptance Criteria**:

- [ ] Define database models based on application requirements.
- [ ] Implement the models in Django.
- [ ] Ensure models are well-documented and tested.

**Tasks**:

- [ ] Design database models based on application requirements.
- [ ] Implement the models in Django.
- [ ] Document and test the models.

**Belonging to**:  EPIC -
