### ISSUE TITLE
[US] DRF - Design Database Models

### ISSUE THREAD

**Issue by JaqiKal** [JaqiKal/pixavibe#8]
**Statement**:

As a developer, I want to design database models so that the data is structured logically.

**Acceptance Criteria**:

- [x] Define database models based on application requirements.
- [x] Implement the models in Django.
- [x] Ensure models are well-documented and tested.

**Tasks**:

- [x] Design database models based on application requirements.
- [x] Implement the models in Django.
- [x] Document and test the models.

**Belonging to**:  EPIC - Development
